### ISSUE TITLE
Cannot reply to a tour comment

### ISSUE THREAD

**Issue by BrianD91** [vsls-contrib/codetour#19]
Just installed the extension and testing it out in MacOS Catalina.

A given comment in the tour has a textarea that one can type into, and it's placeholder text is `Reply...` but after you've finished entering your reply there's no way to submit the form data and save the reply into the tour

**Comment by lostintangent** [comment]
Thanks for reaching out! The `Reply...` text box is unfortunately something that I can't currently hide, since it's a part of the VS Code commenting UX by default. So right now, it's an inert piece of UI that doesn't do anything in a Code Tour.

Out of curiosity: is there something you'd like to be able to use the `Reply...` feature for? My initial plan was to work with the VS Code team, to see if I could get an API to hide it, but I'd also be interested to hear if folks want the `Reply...` functionality for some use case. Thanks!

// CC @egamma for thoughts on being able to hide the `Reply...` textbox

**Comment by ewnd9** [comment]
It could be used as a "code review" of tour steps. Run a tour, comment unclear parts, submit a pr (replies are property in step object).

Person responsible for the tour sees the pr, discusses it, pushes fixes in the same branch with deleting replies, and merges updated tour to master.

**Comment by lostintangent** [comment]
This issue requires some support from VS Code, which is being tracked here: https://github.com/microsoft/vscode/issues/92794. To start, I think I’d like to just be able to hide the “Reply...” input entirely, and then be able to add extra features over time.

// CC @rebornix

**Comment by alpaix** [comment]
The `Reply...` input is very confusing in code tour experience. Where are these replies stored? Who are the participants? I know it's a known issue. It might make sense to call this out in the getting started doc in a known issues of FAQ section.

**Comment by lostintangent** [comment]
The `Reply...` box has now been removed 👍 This change currently only works in VS Code Insiders, but will take affect in VS Code Stable in the next couple of weeks, once the November release goes out.

**Comment by abulka** [comment]
The ability to remove the reply and comment areas has arrived in stable:

> Comment thread reply button visibility.  Comment extensions can now control the visibility of the reply button in a comment thread with a new property, CommentThread#canReply. When it's set to false, users will not see the reply button or comment box in the comment thread.

**Comment by lostintangent** [comment]
Yep! This should now apply to VS Code stable as well 👍
