### ISSUE TITLE
Allow adding steps that point out folders, instead of files

### ISSUE THREAD

**Issue by dodalovic** [vsls-contrib/codetour#40]
First of all - thanks for great extension!

I was thinking that sometimes it's useful to comment on a folder level, rather than the file level. 
Imagine I want to create a codetour step that points out that there some special folder that does some magic or stg. 
Is it somehow doable? 

/cheers

**Comment by gsmile** [comment]
Hi there, thanks for the request and kind words! We will look into how feasible it is to comment on a folder and prioritize based on our backlog. Thank you!

**Comment by stefanforsberg** [comment]
Hello and thanks for an awesome extension!

I've added a code tour that gives a tour of how various smaller services are connected. Currently I've pointed the steps at the main method of the various programs which works but it would make more sense to do so at a folder level since there isn't really a specific line that is important to the tour. So, long way to say 👍 to the feature idea =)

**Comment by michael-golden** [comment]
+1 This would be a wonderful feature.

**Comment by lostintangent** [comment]
Hey all! I just shipped a CodeTour update, which introduces support for [directory steps](https://github.com/vsls-contrib/codetour#directory-steps). While recording a tour, you can now right-click a directory in the `Explorer` tree, select `Add CodeTour Step`, and then specify the description of that directory. Then, when someone plays the tour back, that step will highlight the specified directory and render the description as a comment in a "virtual" folder.

Any feedback would be greatly appreciated. Thanks!
