### ISSUE TITLE
Drag and drop files into CodeTour panel to start a step

### ISSUE THREAD

**Issue by gsmile** [vsls-contrib/codetour#42]
During user testing and getting community feedback, users consistently try to drag files into the CodeTour area to start recording a step of the tour. Perhaps we can enable this functionality, if we can think through the UX of this.

**Comment by lostintangent** [comment]
VS Code doesn't currently support drag and drop for custom tree views, and so we'd need to discuss this with them 👍 

Additionally, since a step is currently associated with not only a file, but also a specific line, we'd need to think through how drag and drop would work (e.g. are you dragging a file or a specific line?)

**Comment by lostintangent** [comment]
I’m going to close this because I don’t think this will be possible for a while, since it’s not on the VS Code team’s current roadmap. We should explore other ways to improve the recording process, and we can always reopen this if we get strong feedback.
