### ISSUE TITLE
Seperate view for CodeTour?

### ISSUE THREAD

**Issue by stefanforsberg** [vsls-contrib/codetour#44]
Hello!

The explorer view tends to get somewhat cluttered with showing file explorer and open editors etc. How would you feel about having the code tour in it's own view (similar to the docker extension below)? 

![image](https://user-images.githubusercontent.com/358570/77992707-e66bd700-7326-11ea-996a-b80e6c1b8ac1.png)

**Comment by lostintangent** [comment]
Yeah I’ve been wondering about this as well. I generally hate adding views to the explorer tab, but I wasn’t sure where else to put it 😁

I’d be interested to hear what other folks think about this suggestion, since the activity bar can also get a little cluttered too. So in general, maybe it’s best if I put the view in the explorer tab as well as a custom tab, and then let folks hide the one they don’t want?

**Comment by alvaromartmart** [comment]
I also think it would be a good idea to add it to the explorer tab. I think cluttering the file explorer is much worse, and the user will still be able to toggle visible tabs on the explorer menu.

**Comment by lostintangent** [comment]
In case folks missed it, VS Code now lets you drag and drop views into its own tab, into built-in tabs, and also into the panel! So even without the CodeTour extension explicitly contributing a separate tab, you could configure it that way today: https://code.visualstudio.com/updates/v1_43#_more-views-are-movable.

**Comment by alefragnani** [comment]
I would say “It depends on extension’s objective”

If its objective is to provide information relative to files, folders or Git, I expect the Panel to be added In Explorer / Git views. Simply because I’m on that context, and I expect to see extension’s additional information there. On the other hand, if the extension provides it’s own information, or relative to the opened Folder/Workspace, I expect it with it’s View.

For instance, the new Timeline panel shows information relative to each file, then adding it to the Explorer view feels more natural.

Speaking about CodeTour, I feel it could have it’s own View, because the information the extension provides is not relative to individual files/folders/git, but the Folder/Workspace you have opened.

Let me know if you open to new contributions 😁

**Comment by lostintangent** [comment]
Now that you can add views to the "panel" (the section that includes the terminal, problems, output panes), I wonder if that represents a good spot for `CodeTour`, since it would be "global" in that sense, whereas, adding it to a new activity bar container, would make it exclusive with the file explorer.

Thoughts? As others are saying, I'm convinced that CodeTour shouldn't be on the `Explorer` tab. However, I'm kind of leaning towards the "panel" being a nicer default location for it. That said, as I mentioned above, you can move the view to any of these locations now, and so we're really just talking about the default location 😄

**Comment by alefragnani** [comment]
> That said, as I mentioned above, you can move the view to any of these locations now, and so we're really just talking about the default location 

That’s true 🤣

I don’t see myself playing with the panels. For better or worse, the default arrangements works pretty well for my dev scenarios. The only customization that I do is “sizing”, depending on full screen / split screen moments. 

But I see your point. With the new panel positioning feature, the user can decide the better location. 

Unfortunately, in my case, I can’t turn a panel Into a new View 🥺. Let’s see if the VSCode team enhances that too.

Thank you!

**Comment by lostintangent** [comment]
I'm going to close this issue for now, since we haven't heard significant feedback here, and also, based on the fact that users can now move this view to wherever they'd like to. Since there's a fairly tight dependency between the `File Explorer` and the `CodeTour` view (e.g. if you have a directory step, you need to have the file explorer visible to know what directory the step is referring to), I think the `CodeTour` view will behave best when placed either in the `File Explorer` (as it currently is) or the panel (along with the terminal). However, since a tour step can also automate running a terminal command, having the `CodeTour` view in the `File Explorer` allows it to be visible at the same time as the `Terminal`, without needing to rely on a split view in the panel.

So having the CodeTour view in the `File Explorer` seems like the best default behavior, and then VS Code allows customizability from there. If folks disagree, please let me know. Thanks!

**Comment by huyz** [comment]
Just a tip: Since it's both desirable to show the File Explorer and the bottom Panel, at different times perhaps, while using Code Tour, I put the Code View in the right sidebar, giving it plenty of space.
