### ISSUE TITLE
getting "git_1.api.getRepository is not a function" error 

### ISSUE THREAD

**Issue by zammew** [vsls-contrib/codetour#57]
hi, i am starting with a project with existing git file, and when i ran the command codeTour: start record, entered title of the tou, i get the error "git_1.api.getRepository is not a function". Am I missing something here?

![image](https://user-images.githubusercontent.com/53103250/80219549-36636280-8675-11ea-9af7-d69596104c14.png)

![image](https://user-images.githubusercontent.com/53103250/80219503-25b2ec80-8675-11ea-91b6-d35182734c2c.png)

**Comment by lostintangent** [comment]
Hmm, that's unexpected! What kind of project did you have opened? And were you connected to a remote context (e.g. WSL, SSH, Docker)?

**Comment by zammew** [comment]
Hi @lostintangent I tried with your source code, it seems that if I deleted `.tours` folder, the error will appear. you can see it from a screen recording of this issue https://streamable.com/u6gy7p 

maybe info about my vscode version could help
![image](https://user-images.githubusercontent.com/53103250/80269202-0a30fb80-86e0-11ea-919c-1c9c229e4ce8.png)

**Comment by lostintangent** [comment]
This issue should now be fixed in the latest CodeTour version. Note that your version of VS Code is a little old, which is why this error occurred. I've worked around it by detecting the absence of the `getRepository` method, but your experience would be improved if you updated to the latest VS Code version. Thanks!
