### ISSUE TITLE
Allow marking main tour

### ISSUE THREAD

**Issue by gsmile** [vsls-contrib/codetour#60]
What if we implement some way for certain tours to be "starred" by default or shown as higher importance? Or, a tagging/categorization mechanism? That way, a new dev onboarding to the codebase will know right away what is most important to view first.

**Comment by lostintangent** [comment]
We’ve already got #50 tracking the ability to group/categorized tours into directories. Should we make this specific to being able to star tours? If so, is the “Star” set by the owner of the repo, or is that something that the individual dev can do?

**Comment by gsmile** [comment]
What if we implement default "stars" and then ability for personal customizations?

**Comment by lostintangent** [comment]
I just renamed this issue, since I think we should use it to track the ability to mark a tour in a codebase as being the “main” tour. This would have two key benefits:

1. When a new user opens the codebase, and are presented with the option to take a tour, they’ll be immediately guided to the the “main” tour as opposed to displaying the entire list of tours. 

1. The “main” tour will be displayed uniquely in the  CodeTour tree (e.g. a unique icon)

**Comment by RandomFractals** [comment]
also, don't let them open the other code tours till they are done with the main one. just kidding

**Comment by lostintangent** [comment]
Support for this has now been shipped. You can simply right-click a tour in the `CodeTour` tree and select `Make Primary`.
