### ISSUE TITLE
Cannot view notebook

### ISSUE THREAD

**Issue by deftomat** [vsls-contrib/codetour#63]
When I try to view the notebook (or open `.tours/quick-start.tour` file), VSCode complains with the following error:

```
Unable to open 'quick-start.tour': Illegal argument: line must be non-negative.
```

My tour file looks like this:
```
{
  "title": "Quick start",
  "steps": [
    {
      "file": "packages/api/package.json",
      "line": 9,
      "description": "### Start API\n\nStart your API locally by running `yarn start` in *packages/api* directory.\n\nIt will start the HTTP server which will be listening on port 3130.\n\n[Try it by yourself!](command:codetour._sendTextToTerminal?%5B%22yarn%20--cwd%20packages%2Fapi%20start%22%5D \"Run \\\"yarn --cwd packages/api start\\\" in a terminal\")"
    },
    {
      "file": "packages/web/package.json",
      "line": 12,
      "description": "### Start React app\nStart your React app by running `yarn start` in `packages/web` directory.\n\n> [yarn start](command:codetour._sendTextToTerminal?%5B%22yarn%20--cwd%20packages%2Fweb%20start%22%5D \"Run \\\"yarn --cwd packages/web start\\\" in a terminal\")"
    }
  ]
}
```

**Comment by lostintangent** [comment]
@deftomat Thanks for reporting this! Which version of the CodeTour extension are you running? `0.0.23`? I just tried to repro this with your exact tour and I'm unfortunately not seeing it.

**Comment by deftomat** [comment]
Extension: 0.0.23
VSCode: 1.44.2
latest macOS

**Comment by deftomat** [comment]
I even try it with all extension disabled (except CodeTour of course)

**Comment by lostintangent** [comment]
Thanks for clarifying that! And just to confirm: you’re simply clicking on the tour file in the file tree and seeing this error? Are you seeing the error in the dev console or are you getting an error notification toast?

**Comment by deftomat** [comment]
Notification toast. For both clicking on tour file and also by invoking
"view notebook" trough the context menu.

Tomáš Szabo

**Comment by lostintangent** [comment]
Ah OK cool. But if you click the play button for the tour, or right-click the tour and select `Start Tour`, then it works? I actually disabled the notebook feature for now, since it's only a proposed API in VS Code. I thought I shipped an update to remove it, but I just realized that I didn't. So I'll ship that update, and close this issue, since the notebook feature isn't unfortunately officially supported yet.

Please re-open this if you're seeing issues with trying to play/start a code using the non-notebook view. Also, the update I'll ship right now will fix the ability to click on a tour file and view it.

**Comment by deftomat** [comment]
Ok. Thanks!

Hopefully, notebook view will be back soon.

**Comment by lostintangent** [comment]
Yep it will! 👍
