### ISSUE TITLE
[enhancement] Move/copy steps from one tour to another

### ISSUE THREAD

**Issue by alvaromartmart** [vsls-contrib/codetour#67]
It may be useful to have the ability to move or copy tour steps from one tour to another, using drag & drop from the codetour panel.

This would make it easier to, for instance, split a long tour into smaller tours - though I guess it can also be achieved by simply copying the .tour file and removing the unwanted steps.

**Comment by lostintangent** [comment]
Unfortunately, the VS Code tree view doesn't support drag-and-drop, and I haven't seen any plans for that being possible anytime soon. That said, I wonder if two things might help here:

* Adding a `Duplicate Tour` command to the tree view, which asks you for a name and simply creates a new tour file based on the original. 
* Add support for multi-select delete in the `CodeTour` tree. That way, you could duplicate a tour and then easily delete the steps in the new tour that you don't need.

As you said, both of these could already be achieved by duplicating the `*.tour` file and then removing the unwanted steps. But the above might be a nice "accelerator", since the existing recorder tries to abstract away the file editing process for common tasks.

**Comment by lostintangent** [comment]
I just checked in support for multi-select deletion of tour steps. That way, you can duplicate a tour file and then multi-select the steps you don't want, and then delete them. As I mentioned above, I think this is the best I'll be able to do for a while, until VS Code adds drag-and-drop support to the tree views.

I also contemplated adding a `Duplicate Tour` command to the tree view, but since this is basically just creating a new file, I didn't want to clutter the context menu with a command that might not be too commonly used.

I'm going to close this as resolved with the multi-select delete support. But please let me know if you don't agree with that design choice 😄 Thanks for the feedback!

**Comment by alvaromartmart** [comment]
Thanks! Too bad the tree views do not yet support drag & drop, but this definitely helps.
