### ISSUE TITLE
Allow to execute commands 

### ISSUE THREAD

**Issue by jeluard** [vsls-contrib/codetour#70]
Great work on codetour!

In order to improve user interactivity, have you considered allowing to execute commands as part of tour steps? Some buttons could allow end users to trigger those.
[ShepperdJS](https://shepherdjs.dev/) does that kind of things and it greatly improves tours IMO.

**Comment by lostintangent** [comment]
Hey! Yes this is definitely something I’d like to add 🤗 CodeTour currently supports adding [shell commands](https://github.com/vsls-contrib/codetour/blob/master/README.md#shell-commands) to a step, and it would be a simple addition to allow calling arbitrary VS Code commands. Out of curiosity: do you have any specific actions/commands in mind?

**Comment by RandomFractals** [comment]
I think having any vscode commands be invliked in a tour step could make it possible to even demo custom extensions.

For example, I've been thinking about creating a code tour to demo [Data Preview](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview) If I could specify vscode commands in tour steps, I could add `data.preview <somePublicDataUrl>` for a brief display of what it does ...

**Comment by jeluard** [comment]
Right, pretty much what @RandomFractals said! Would be a great way to showcase other extensions :)
Another use-case I had in mind: open a rendered markdown file, open a preview browser, ..

You could probably even reuse it to trigger different tour flows e.g. skip some steps

**Comment by RandomFractals** [comment]
yeah, could open a lot of opportunities. Since code tour is one of the gistfs/gistpad dependencies I was thinking one could even pull in gists in gistpad and create a code tour for a gist with refs to code lines and light docs about what they do in addition to typical gist md docs.

**Comment by jeluard** [comment]
@lostintangent Would you be interested with help on this one?

**Comment by lostintangent** [comment]
I pushed a change in `v0.0.026` that ensures this is possible 😄 But I think there can potentially be some improvements to the experience to better optimize certain workflows (e.g. similar to how I introduced the `>>` syntax for adding shell commands to a tour step).

To make use of this, you can simply add a markdown link to a step's description, and instead of it being an HTTP URL, you can point it at a `command:` URL that references the name of the VS Code command that you want to call when the end-user clicks the link. For example, the following illustrates how you could add a link to call a command that doesn't require any parameters.

```markdown
[Link Title](command:extensionName.commandName "Optional link title")
```

If the VS Code command requires parameters, then you simply define them as a JavaScript array, [URL-encode them](https://www.urlencoder.org/), and then add that string as a query string of the command URL. For example, to pass `"foo"` to a command, the URL would look like the following: `command:extensionName.commandName?%5B%22foo%22%5D`

**Comment by lostintangent** [comment]
I just shipped an update to CodeTour that makes two additional improvements:

1. It automatically encodes your command arguments, in order to make the authoring process simpler
1. It now includes a completion provider, for prompting you with common commands as soon as you type `(command:`. This way, you don't have to remember the name or arguments for basic scenarios (e.g. navigating to another tour/step, launching a URL, running a shell command).

![Commands](https://user-images.githubusercontent.com/116461/82712888-09877880-9c3e-11ea-953f-603fca2d7f64.gif)

With this, you should have everything you need to call any command from a tour step. That said, I'd love to hear if there are other commonly-used commands, that would benefit from being added to the completion list. Thanks again for the feedback and let me know how I can improve things further!

**Comment by alexey1935** [comment]
Wow thanks a ton! This is seriously awesome!

**Comment by jamiebarrow** [comment]
This works for me with opening the file, however I was wondering if I'd be able to run the command `markdown.showPreview` in order to open the preview of an existing Markdown file in the codebase from a link in the CodeTour step.

i.e. `./docs/CONTRIBUTING.md` but in Markdown preview mode.
