### ISSUE TITLE
Provide direct vsix links

### ISSUE THREAD

**Issue by jeluard** [vsls-contrib/codetour#76]
Some environment (e.g. [theia](https://theia-ide.org)) cannot use the official marketplace for legal reason. An alternative is to host vsix as part of github release (as done [here](https://github.com/rust-analyzer/rust-analyzer/releases)).

Is that an option for codetour?

**Comment by jeluard** [comment]
@lostintangent is this something you would accept a contribution for?

**Comment by lostintangent** [comment]
Sorry for the late reply! I believe the VS marketplace already provides links to the VSIX directly. Would that satisfy the need here?

**Comment by jeluard** [comment]
Actually I don't think they do provide direct curlable link, and it would probably be against terms of use.

An alternative would be to deploy on an open marketplace like https://open-vsx.org/

**Comment by lostintangent** [comment]
It appears as if someone has already [published CodeTour](https://open-vsx.org/extension/vsls-contrib/codetour) to the Open VSX marketplace? Since I’m still iterating pretty heavily on the experience, and am very focused on supporting VS Code, I think it makes sense for the community to handle publishing to other marketplaces. That said, I’m going to close this. Not because I don’t care, I just don’t have the time to support it :/ As your other bug calls out, publishing these direct links isn’t just about generating vsix releases, it also requires testing the extension in other environments.

**Comment by jeluard** [comment]
Makes sense! Great to see that it's been uploaded on open-vsx.
