### ISSUE TITLE
CodeTour fails in Theia

### ISSUE THREAD

**Issue by jeluard** [vsls-contrib/codetour#80]
CodeTour fails when running in [Theia](https://github.com/eclipse-theia/theia) because of a missing `TextEncoder` import.
Adding the following line fixes the issue.

```js
import { TextEncoder } from 'util';
```

See https://github.com/eclipse-theia/theia/issues/7980

**Comment by gsmile** [comment]
Thanks for letting us know! We will look into how to include it by default for running in Theia.

**Comment by lostintangent** [comment]
I'm going to close this for now, since I unfortunately don't have the bandwidth to test/maintain CodeTour in any environment other than VS Code directly. If the community wants to help support Theia, then PRs are completely welcome. But I suspect that there will be other subtle interop issues now and in the future, and so I want to be clear about what support is expected 👍
