### ISSUE TITLE
line vs selection

### ISSUE THREAD

**Issue by LucianoBestia** [vsls-contrib/codetour#81]
In my experience with CodeTour the "line" is not important at all and should be removed.
Only the "selection" is important and should be made mandatory.
```json
            "line": 104,
            "selection": {
                "start": {
                    "line": 101,
                    "character": 1
                },
                "end": {
                    "line": 104,
                    "character": 7
                }
```
I expect now questions to describe the problem.
Most of the languages are multi-line today. The first line sounds like the most important.
But if I use it for "line", then the editor window shows only that line and push out of sight the other lines of the same statement. 
example line 99 is the start of the statement:
![image](https://user-images.githubusercontent.com/31509965/84774406-68e96600-affb-11ea-9f7c-660d9100d0fc.png)

If I want to see the whole statement I need to use the line with the last delimiter. That is not really an important line.
Example if I use the line 103, but it is only ending braces:
![image](https://user-images.githubusercontent.com/31509965/84774686-d1d0de00-affb-11ea-9de5-c0c2d04432e9.png)

So the conclusion is that "selection" is much more suited to modern languages:
![image](https://user-images.githubusercontent.com/31509965/84774952-296f4980-affc-11ea-859b-71f10e211115.png)

**Comment by lostintangent** [comment]
As you’ve demonstrated, you can select entire lines of code and then attach your comments to it. Does the presence of the line property inhibit the ability to create the experience you want? Maybe I could simplify the experience of annotating a selection by allowing you to select a block of text and then right click the editor and selecting “Add CodeTour Step”?

I’m likely to remove the need for the line property anyways, in order to improve your tour resilience. But I hesitate to make selections mandatory at this point, since a lot of people are using CodeTour. That said, I think we can make the creation of selection-based tours easier to do. Thoughts?

**Comment by LucianoBestia** [comment]
I am happy with the way to select a selection. Also updating the selection is great and easy. Maybe making the last line of the selection automatically the "line number" after updating could be nice. So the last line of the selection could always be the "line number".

**Comment by gsmile** [comment]
Thanks for the suggestion. So, what you really want to do, is be able to view the entire block of code being referenced, while having the tour step open. And right now, locking the step to the first line doesn't let you do that because it covers the code. It's a good point. We will look into fixing this issue.

**Comment by lostintangent** [comment]
Hey! So I just shipped an update that allows two things:

1. You can create new steps from a selection by simply selecting a span of text, right-clicking the editor and selecting `Add CodeTour Step`. That step will now be associated with the final line of the selection. If you edit the step to adjust the selection, then the resulting line number association will updated along with it.

2. The tour recorder now allows you to easily edit the line number of a step. When recording, you can click the `...` menu of the current step, and select `Change Line`. If you clear the line number value, that will "convert" the step from being locked to a specific line, to be associated with a selection instead.

As a result of these two changes, I'm going to close this issue as resolved, but please let me know if you have any other feedback. Thanks!
