### ISSUE TITLE
One-click code snippet addition

### ISSUE THREAD

**Issue by gsmile** [vsls-contrib/codetour#97]
For certain training materials, snippets of code are inserted into the file as a follow-along build-your-own app.
A customer is looking for functionality for tour steps to implement one-click addition of code inside the file.

Scenario:
- Developer is following a learning lab
- CodeTour step includes a code snippet with a link that says "Insert code"
- Developer clicks on link that says "Insert code"
- Code is inserted in the correct location in the file
- Developer moves onto next steps

Considerations:
- As tour steps are associated with line numbers, this changes the context of the following tour steps
- KataCoda (acquired by Wiley) uses this feature for online learning

**Comment by lostintangent** [comment]
Closing this as resolved 🚀 Now, if you add a markdown code block to a step, CodeTour will render an `Insert Code` link underneath that code snippet. When the end-user clicks that, the associated code block will be inserted into the current line, and them formatted to match the rest of the document.

I suspect that we'll lots of feedback in order to refine this experience in practice, but I think it's sufficient enough to start playing with and getting feedback 👍 

![Snippet](https://user-images.githubusercontent.com/116461/98431597-bb3f2800-206b-11eb-8f46-55f48ff014ef.gif)
